auto_scale_lr = dict(base_batch_size=16, enable=False)
backend_args = None
class_names = [
    'car',
    'bicycle',
    'motorcycle',
    'truck',
    'bus',
    'person',
    'bicyclist',
    'motorcyclist',
    'road',
    'parking',
    'sidewalk',
    'other-ground',
    'building',
    'fence',
    'vegetation',
    'trunck',
    'terrian',
    'pole',
    'traffic-sign',
]
custom_imports = dict(
    allow_failed_imports=False, imports=[
        'bevseg',
    ])
data_root = 'data/semantickitti/'
dataset_type = 'SemanticKittiDataset'
default_hooks = dict(
    checkpoint=dict(
        by_epoch=False, interval=-1, save_best='miou', type='CheckpointHook'),
    logger=dict(interval=50, type='LoggerHook'),
    param_scheduler=dict(type='ParamSchedulerHook'),
    sampler_seed=dict(type='DistSamplerSeedHook'),
    timer=dict(type='IterTimerHook'),
    visualization=dict(type='Det3DVisualizationHook'))
default_scope = 'mmdet3d'
env_cfg = dict(
    cudnn_benchmark=False,
    dist_cfg=dict(backend='nccl'),
    mp_cfg=dict(mp_start_method='fork', opencv_num_threads=0))
input_modality = dict(use_camera=False, use_lidar=True)
labels_map = dict({
    0: 19,
    1: 19,
    10: 0,
    11: 1,
    13: 4,
    15: 2,
    16: 4,
    18: 3,
    20: 4,
    252: 0,
    253: 6,
    254: 5,
    255: 7,
    256: 4,
    257: 4,
    258: 3,
    259: 4,
    30: 5,
    31: 6,
    32: 7,
    40: 8,
    44: 9,
    48: 10,
    49: 11,
    50: 12,
    51: 13,
    52: 19,
    60: 8,
    70: 14,
    71: 15,
    72: 16,
    80: 17,
    81: 18,
    99: 19
})
launcher = 'none'
load_from = None
log_level = 'INFO'
log_processor = dict(by_epoch=False, type='LogProcessor', window_size=50)
metainfo = dict(
    classes=[
        'car',
        'bicycle',
        'motorcycle',
        'truck',
        'bus',
        'person',
        'bicyclist',
        'motorcyclist',
        'road',
        'parking',
        'sidewalk',
        'other-ground',
        'building',
        'fence',
        'vegetation',
        'trunck',
        'terrian',
        'pole',
        'traffic-sign',
    ],
    max_label=259,
    seg_label_mapping=dict({
        0: 19,
        1: 19,
        10: 0,
        11: 1,
        13: 4,
        15: 2,
        16: 4,
        18: 3,
        20: 4,
        252: 0,
        253: 6,
        254: 5,
        255: 7,
        256: 4,
        257: 4,
        258: 3,
        259: 4,
        30: 5,
        31: 6,
        32: 7,
        40: 8,
        44: 9,
        48: 10,
        49: 11,
        50: 12,
        51: 13,
        52: 19,
        60: 8,
        70: 14,
        71: 15,
        72: 16,
        80: 17,
        81: 18,
        99: 19
    }))
model = dict(
    backbone=dict(
        circular_padding=False,
        double_version=True,
        down_chs=(
            128,
            256,
            512,
            512,
        ),
        in_ch=32,
        inc_ch=64,
        type='Unet',
        up_chs=(
            256,
            128,
            64,
            64,
        )),
    bev_encoder=dict(
        feat_channels=[
            64,
            128,
            256,
        ],
        feat_compression=32,
        in_channels=7,
        type='BevFeatureEncoder',
        with_pre_norm=True),
    data_preprocessor=dict(
        grid_shape=[
            480,
            360,
            32,
        ],
        ignore_index=19,
        point_cloud_range=[
            -50,
            -50,
            -3,
            50,
            50,
            1.5,
        ],
        type='VoxelPreprocessor',
        voxel_type='cubic'),
    decode_head=dict(
        channels=64,
        conv_seg_kernel_size=1,
        dropout_ratio=0,
        ignore_index=19,
        loss_ce=dict(
            avg_non_ignore=True,
            class_weight=None,
            loss_weight=1.0,
            type='mmdet.CrossEntropyLoss',
            use_sigmoid=False),
        loss_lovasz=dict(loss_weight=1.0, reduction='none', type='LovaszLoss'),
        n_height=32,
        num_classes=20,
        type='BevHead'),
    type='BevNet')
optim_wrapper = dict(
    optimizer=dict(
        betas=(
            0.9,
            0.999,
        ), eps=1e-08, lr=0.02, type='Adam', weight_decay=0),
    type='OptimWrapper')
resume = False
test_cfg = dict()
test_dataloader = dict(
    batch_size=4,
    dataset=dict(
        ann_file='semantickitti_infos_val.pkl',
        backend_args=None,
        data_root='data/semantickitti/',
        ignore_index=19,
        metainfo=dict(
            classes=[
                'car',
                'bicycle',
                'motorcycle',
                'truck',
                'bus',
                'person',
                'bicyclist',
                'motorcyclist',
                'road',
                'parking',
                'sidewalk',
                'other-ground',
                'building',
                'fence',
                'vegetation',
                'trunck',
                'terrian',
                'pole',
                'traffic-sign',
            ],
            max_label=259,
            seg_label_mapping=dict({
                0: 19,
                1: 19,
                10: 0,
                11: 1,
                13: 4,
                15: 2,
                16: 4,
                18: 3,
                20: 4,
                252: 0,
                253: 6,
                254: 5,
                255: 7,
                256: 4,
                257: 4,
                258: 3,
                259: 4,
                30: 5,
                31: 6,
                32: 7,
                40: 8,
                44: 9,
                48: 10,
                49: 11,
                50: 12,
                51: 13,
                52: 19,
                60: 8,
                70: 14,
                71: 15,
                72: 16,
                80: 17,
                81: 18,
                99: 19
            })),
        modality=dict(use_camera=False, use_lidar=True),
        pipeline=[
            dict(
                backend_args=None,
                coord_type='LIDAR',
                load_dim=4,
                type='LoadPointsFromFile',
                use_dim=4),
            dict(
                backend_args=None,
                dataset_type='semantickitti',
                seg_3d_dtype='np.int32',
                seg_offset=65536,
                type='LoadAnnotations3D',
                with_bbox_3d=False,
                with_label_3d=False,
                with_seg_3d=True),
            dict(type='PointSegClassMapping'),
            dict(
                keys=[
                    'points',
                ],
                meta_keys=[
                    'num_points',
                ],
                type='Pack3DDetInputs'),
        ],
        test_mode=True,
        type='SemanticKittiDataset'),
    drop_last=False,
    num_workers=4,
    persistent_workers=True,
    sampler=dict(shuffle=False, type='DefaultSampler'))
test_evaluator = dict(type='SegMetric')
test_pipeline = [
    dict(
        backend_args=None,
        coord_type='LIDAR',
        load_dim=4,
        type='LoadPointsFromFile',
        use_dim=4),
    dict(
        backend_args=None,
        dataset_type='semantickitti',
        seg_3d_dtype='np.int32',
        seg_offset=65536,
        type='LoadAnnotations3D',
        with_bbox_3d=False,
        with_label_3d=False,
        with_seg_3d=True),
    dict(type='PointSegClassMapping'),
    dict(
        keys=[
            'points',
        ], meta_keys=[
            'num_points',
        ], type='Pack3DDetInputs'),
]
train_cfg = dict(
    max_iters=160000, type='IterBasedTrainLoop', val_interval=2000)
train_dataloader = dict(
    batch_size=2,
    dataset=dict(
        ann_file='semantickitti_infos_train.pkl',
        backend_args=None,
        data_root='data/semantickitti/',
        ignore_index=19,
        metainfo=dict(
            classes=[
                'car',
                'bicycle',
                'motorcycle',
                'truck',
                'bus',
                'person',
                'bicyclist',
                'motorcyclist',
                'road',
                'parking',
                'sidewalk',
                'other-ground',
                'building',
                'fence',
                'vegetation',
                'trunck',
                'terrian',
                'pole',
                'traffic-sign',
            ],
            max_label=259,
            seg_label_mapping=dict({
                0: 19,
                1: 19,
                10: 0,
                11: 1,
                13: 4,
                15: 2,
                16: 4,
                18: 3,
                20: 4,
                252: 0,
                253: 6,
                254: 5,
                255: 7,
                256: 4,
                257: 4,
                258: 3,
                259: 4,
                30: 5,
                31: 6,
                32: 7,
                40: 8,
                44: 9,
                48: 10,
                49: 11,
                50: 12,
                51: 13,
                52: 19,
                60: 8,
                70: 14,
                71: 15,
                72: 16,
                80: 17,
                81: 18,
                99: 19
            })),
        modality=dict(use_camera=False, use_lidar=True),
        pipeline=[
            dict(
                backend_args=None,
                coord_type='LIDAR',
                load_dim=4,
                type='LoadPointsFromFile',
                use_dim=4),
            dict(
                backend_args=None,
                dataset_type='semantickitti',
                seg_3d_dtype='np.int32',
                seg_offset=65536,
                type='LoadAnnotations3D',
                with_bbox_3d=False,
                with_label_3d=False,
                with_seg_3d=True),
            dict(type='PointSegClassMapping'),
            dict(
                flip_ratio_bev_horizontal=0.5,
                flip_ratio_bev_vertical=0.5,
                sync_2d=False,
                type='RandomFlip3D'),
            dict(
                rot_range=[
                    -3.1415926,
                    3.1415926,
                ],
                scale_ratio_range=[
                    0.95,
                    1.05,
                ],
                translation_std=[
                    0.1,
                    0.1,
                    0.1,
                ],
                type='GlobalRotScaleTrans'),
            dict(
                keys=[
                    'points',
                    'pts_semantic_mask',
                ], type='Pack3DDetInputs'),
        ],
        type='SemanticKittiDataset'),
    num_workers=2,
    persistent_workers=True,
    sampler=dict(shuffle=True, type='DefaultSampler'))
train_pipeline = [
    dict(
        backend_args=None,
        coord_type='LIDAR',
        load_dim=4,
        type='LoadPointsFromFile',
        use_dim=4),
    dict(
        backend_args=None,
        dataset_type='semantickitti',
        seg_3d_dtype='np.int32',
        seg_offset=65536,
        type='LoadAnnotations3D',
        with_bbox_3d=False,
        with_label_3d=False,
        with_seg_3d=True),
    dict(type='PointSegClassMapping'),
    dict(
        flip_ratio_bev_horizontal=0.5,
        flip_ratio_bev_vertical=0.5,
        sync_2d=False,
        type='RandomFlip3D'),
    dict(
        rot_range=[
            -3.1415926,
            3.1415926,
        ],
        scale_ratio_range=[
            0.95,
            1.05,
        ],
        translation_std=[
            0.1,
            0.1,
            0.1,
        ],
        type='GlobalRotScaleTrans'),
    dict(keys=[
        'points',
        'pts_semantic_mask',
    ], type='Pack3DDetInputs'),
]
val_cfg = dict()
val_dataloader = dict(
    batch_size=4,
    dataset=dict(
        ann_file='semantickitti_infos_val.pkl',
        backend_args=None,
        data_root='data/semantickitti/',
        ignore_index=19,
        metainfo=dict(
            classes=[
                'car',
                'bicycle',
                'motorcycle',
                'truck',
                'bus',
                'person',
                'bicyclist',
                'motorcyclist',
                'road',
                'parking',
                'sidewalk',
                'other-ground',
                'building',
                'fence',
                'vegetation',
                'trunck',
                'terrian',
                'pole',
                'traffic-sign',
            ],
            max_label=259,
            seg_label_mapping=dict({
                0: 19,
                1: 19,
                10: 0,
                11: 1,
                13: 4,
                15: 2,
                16: 4,
                18: 3,
                20: 4,
                252: 0,
                253: 6,
                254: 5,
                255: 7,
                256: 4,
                257: 4,
                258: 3,
                259: 4,
                30: 5,
                31: 6,
                32: 7,
                40: 8,
                44: 9,
                48: 10,
                49: 11,
                50: 12,
                51: 13,
                52: 19,
                60: 8,
                70: 14,
                71: 15,
                72: 16,
                80: 17,
                81: 18,
                99: 19
            })),
        modality=dict(use_camera=False, use_lidar=True),
        pipeline=[
            dict(
                backend_args=None,
                coord_type='LIDAR',
                load_dim=4,
                type='LoadPointsFromFile',
                use_dim=4),
            dict(
                backend_args=None,
                dataset_type='semantickitti',
                seg_3d_dtype='np.int32',
                seg_offset=65536,
                type='LoadAnnotations3D',
                with_bbox_3d=False,
                with_label_3d=False,
                with_seg_3d=True),
            dict(type='PointSegClassMapping'),
            dict(
                keys=[
                    'points',
                ],
                meta_keys=[
                    'num_points',
                ],
                type='Pack3DDetInputs'),
        ],
        test_mode=True,
        type='SemanticKittiDataset'),
    drop_last=False,
    num_workers=4,
    persistent_workers=True,
    sampler=dict(shuffle=False, type='DefaultSampler'))
val_evaluator = dict(type='SegMetric')
vis_backends = [
    dict(type='LocalVisBackend'),
]
visualizer = dict(
    name='visualizer',
    type='Det3DLocalVisualizer',
    vis_backends=[
        dict(type='LocalVisBackend'),
    ])
work_dir = './work_dirs/bevseg_semantickitti_stlr'
